#!/bin/bash

jupyter nbconvert analysis.ipynb --to html --output analysis-with-code.html
mv analysis-with-code.html doc

jupyter nbconvert analysis.ipynb --no-input --to html --output index.html
mv index.html doc
